const { RECORDING_REASONS } = require("./recordingReasons");

const EVENT_AUTO_RESOLVE_MS = {
  [RECORDING_REASONS.DOOR_OPEN]: 15_000,        // 15 sec
  [RECORDING_REASONS.HELP_BUTTON]: 30_000,
  [RECORDING_REASONS.KIOSK_INTERACTION]: 20_000,
  [RECORDING_REASONS.SUPPORT_AGENT]: 60_000,
};

module.exports = { EVENT_AUTO_RESOLVE_MS };
